### ISSUE TITLE
出错

### ISSUE THREAD

**Issue by xiaoming140** [xyTom/Url-Shorten-Worker#11]
404 Not Found.
The url you visit is not found.

**Comment by xiaoming140** [comment]
还有，自己搭建的是可以永久保存吗

**Comment by xiaoming140** [comment]
# 能不能在页面就只定义而不用麻烦的跑到kv里再搞一次？

**Comment by xyTom** [comment]
> 还有，自己搭建的是可以永久保存吗

自己搭建的是可以永久保存的，Demo是为了防止有人滥用，故意引导到一些恶意网站，所以设置了限制

**Comment by xyTom** [comment]
> # 能不能在页面就只定义而不用麻烦的跑到kv里再搞一次？

暂时没有设计这个功能
