### ISSUE TITLE
能不能随便加一个去除ref的功能

### ISSUE THREAD

**Issue by jsjcjsjc** [xyTom/Url-Shorten-Worker#16]
大佬,能不能随便加一个去除ref的功能啊
感谢

**Comment by xyTom** [comment]
已添加，请部署最新的代码，并修改config中的 no_ref    ###为on，开启此功能。

config示例：
```
const config = {
no_ref: "on", 
theme:"",
cors: "on",
}
```

**Comment by jsjcjsjc** [comment]
太感谢了,我去论坛吹一波~~

**Comment by jsjcjsjc** [comment]
有两个问题:
1.选择输出ref 后的跳转界面是必须的吗？
2.我看到代码里有两个外部引用文件，可以一起放到github中吗，方便fork，我怕大佬删库…

小白提问，怪不好意思的
同学可以放一个链接啊，我看到很多程序员都有个请咖啡的链接，这个短网址很和我口味啊，想起同学喝几杯咖啡
~o(〃'▽'〃)o

**Comment by xyTom** [comment]
> 有两个问题: 1.选择输出ref 后的跳转界面是必须的吗？ 2.我看到代码里有两个外部引用文件，可以一起放到github中吗，方便fork，我怕大佬删库… 3.这个程序如果用worker的收费版可以承受每天5k流量的跳转吗
> 
> 小白提问，怪不好意思的 同学可以放一个链接啊，我看到很多程序员都有个请咖啡的链接，这个短网址很和我口味啊，想起同学喝几杯咖啡 ~o(〃'▽'〃)o

1、是必须要有的，因为如果直接返回http 301代码（原本代码的跳转方式）进行跳转无法去除Referer，必须通过html页面中加入noreferrer标签才能让浏览器跳转的时候不带Referer。但可以修改no-ref.html中的代码，减少跳转等待时间。
2、两个外部引用文件已经在（一直都在）github中，只是位于gh-pages分支（需要手动切换一下）。或者使用下面的链接直达：[https://github.com/xyTom/Url-Shorten-Worker/tree/gh-pages](https://github.com/xyTom/Url-Shorten-Worker/tree/gh-pages)  你可以直接fork本项目到你自己的账号中，Github会同时将两个分支都复制到你的账号里面。
3、这个程序在代码上没有对流量进行限制，唯一的限制便是Cloudflare本身的免费额度限制，具体可以查看Cloudflare的官方文档：[https://developers.cloudflare.com/workers/platform/limits#worker-limits](https://developers.cloudflare.com/workers/platform/limits#worker-limits) 理论上来说，购买worker的付费计划应该是可以解除限制的（我没有够买过，故未曾研究其计费规则和相关限制），但一般来说免费版的额度也足够使用。

**Comment by xyTom** [comment]
上次发布的代码存在bug，生成的链接会在24小时后自动删除，可能需要麻烦您重新部署一下。非常抱歉，由于最近一段时间都在忙于准备各种考试，没有太多的时间，上次发布的代码比较匆忙，没有仔细检查，导致错误包含了演示网站中24小时删除生成链接的代码。现在已发布修复该问题的代码，麻烦您重新部署最新版本的代码。给您带来了不便，非常抱歉！

#22
