### ISSUE TITLE
能不能新增一個密碼功能呢？

### ISSUE THREAD

**Issue by HuJK** [xyTom/Url-Shorten-Worker#17]
新增密碼功能，輸入密碼才能新增短網址
for 自用，別人不能新增

**Comment by xyTom** [comment]
Cloudflare已经提供了相关的访问控制功能（有免费额度），故不再重复添加此类功能，如实在想加入，欢迎pull request。

如需限制新增请使用Cloudflare Access，具体配置请查看Cloudflare官网
[https://www.cloudflare.com/zh-cn/teams/access/](https://www.cloudflare.com/zh-cn/teams/access/)
