### ISSUE TITLE
自己部署的worker中，一天后短链无法访问

### ISSUE THREAD

**Issue by Nigel-NI** [xyTom/Url-Shorten-Worker#22]
将index.js的内容复制到自己的cf worker空间中，配置了KV namespace，绑定了自己的域名。转成短链后，约1天内链接访问正常，KV里有记录可查；但是一天后短链无法跳转，KV记录被清空，期间我没有对自己部署的项目进行任何干涉。请问是哪里出了问题呢？

**Comment by xyTom** [comment]
很抱歉，是上一次commit的代码存在问题，忘记去除了Demo生成的链接24小时的限制，现在已经重新提交了新的代码，去除了相关的限制，麻烦重新部署一下新的代码，应该新的代码就没有问题了。非常感谢您的反馈。
