### ISSUE TITLE
Whats the use case if data needs to be parsed ?

### ISSUE THREAD

**Issue by tobidev615** [xyTom/Url-Shorten-Worker#29]
Came across the great project and it has been really handy. 
There is this confusing part with links that contains variable.
E.G: Destination Link: https://my.domain.com/referals/?name=Tom 

How is it possible to achieve the value for the variable name in the destination url as each click has it unique name value.

**Comment by xyTom** [comment]
(1) If you mean passing variables to the destination url, I'd have to say that's a feature that could be implemented, but the current version of the code doesn't implement this feature and would require some modification of the code.
(2) If you mean that you need to generate destination url containing different variables, then you just need to modify the variable in the destination url and generate short links multiple times.

For example,
If you want achieve (1), that is using the same short url for different variable. 
Like: https://xx.xx/abcde?name=Tom ==> https://example.com?name=Tom
https://xx.xx/abcde?name=Tobi ==> https://example.com?name=Tobi
That may need to modify following part of the code to pass throught the character after '?' when redirect to the Destination
https://github.com/xyTom/Url-Shorten-Worker/blob/779653193d066a7b1267c2288a46d36b171a1c9e/index.js#L124-L155

If you want to achieve (2), that is using different short url for different variable.
Like: https://xx.xx/abcde ==>  https://example.com?name=Tom
https://xx.xx/fghij ==>  https://example.com?name=Tobi
That not need to modify the code, just use the API or Webpage to generate short link for twice.

**Comment by tobidev615** [comment]
Thanks for the swift reply. I'm trying to implement use case 1. The destination url needs the value from each link to know what to display to the person. 
I have tried some functions but i keep getting stuck. 
One major challenge when trying to implement my functions is that when i want to generate short url, do i include the parameters without value or paste the link in the shortener without any "?" parameters then append the parameters added to the redirect link when my redirect link is clicked.

**Comment by dras51** [comment]
#30

**Comment by xyTom** [comment]
Thank you!  @dras51 

The code has been updated, just deploy the new version of the code to use the feature. When you generate the short link, you not need to include the any params (variable).

For example, when you use the new version of the code, the url-shorten-worker will behave as following,

https://xx.xx/abcde?name=Tom ==> https://example.com?name=Tom
https://xx.xx/abcde?name=Tobi ==> https://example.com?name=Tobi

And when you generate the link, you only need to input: https://example.com
