### ISSUE TITLE
请问短链能自定义吗？

### ISSUE THREAD

**Issue by shangrenxi** [xyTom/Url-Shorten-Worker#5]
谢谢dalao的付出，已经部署上了。

现在生成的是不规则的，希望生成可自定义的，这样我发给朋友时就不用检查短链是否正确了。
如名称有重复的，则最新覆盖旧的自定义名称。

**Comment by xyTom** [comment]
可以自定义的，在Cloudflare Workers的管理页面点击KV选项卡，手动添加一条KV记录即可
