### ISSUE TITLE
crazypeace 修改版的安全漏洞

### ISSUE THREAD

**Issue by lwd-temp** [xyTom/Url-Shorten-Worker#59]
https://github.com/xyTom/Url-Shorten-Worker/blob/crazypeace/index.js

当 no_ref: "on" 时，直接访问 /password 路径即可绕过密码验证。

源码中没有努力规避这个问题。

**Comment by crazypeace** [comment]
感谢!

目前在我的fork已处理.
https://github.com/crazypeace/url-Shorten-Worker/

https://github.com/crazypeace/Url-Shorten-Worker/blob/da5b5ae24125947e7415a869e09db94af5243fe9/worker.js#L319
