### ISSUE TITLE
添加跨源资源共享（CORS）支持

### ISSUE THREAD

**Issue by Misaka13514** [xyTom/Url-Shorten-Worker#6]
在网站上尝试调用API时遇到的问题

```
Request header field Content-Type is not allowed by Access-Control-Allow-Headers.
XMLHttpRequest cannot load https://5it.me/ due to access control checks.
Failed to load resource: Request header field Content-Type is not allowed by Access-Control-Allow-Headers.
```

自己尝试修改js没成功，能否请dalao帮助解决

**Comment by xyTom** [comment]
最近在忙别的事情，暂时没时间维护这个项目，可能需要过几天才有空。

**Comment by xyTom** [comment]
已经添加标头:
> Access-Control-Allow-Origin: *
> Access-Control-Allow-Methods: POST


Javascript请求API示例代码：
`var data = JSON.stringify({"url":"Your_URL"});
var xhr = new XMLHttpRequest();
xhr.addEventListener("readystatechange", function() {
  if(this.readyState === 4) {
    console.log(this.responseText);
  }
});
xhr.open("POST", "https://5it.me/");
xhr.send(data);`
