### ISSUE TITLE
不在worker.js里面实现跳转, 而是用no-ref.html实现, 会有什么不好的副作用吗?

### ISSUE THREAD

**Issue by crazypeace** [xyTom/Url-Shorten-Worker#66]
大佬你好!
我有一个构想,  worker.js 里面不实现跳转, 把短链系统的跳转放到 no-ref.html实现,
估且认为这是 result.html

这样, 可以通过使用不同的 index.html 和 result.html 来实现不同的功能.
比如, 图床, MarkDown格式显示, 等...

我知道短链系统的跳转通过 no-ref.html 是可以实现基本功能的.
但是, 担心有什么考虑不周的副作用.
你应用这个短链系统要早非常多, 请问是否已经想过这个问题? 已经有什么答案了吗？

**Comment by xyTom** [comment]
我之前确实有考虑过类似的思路，通过不同的 index.html 和 result.html 实现不同的功能，具有很大的灵活性。但因为需要的功能相对简单，所以选择直接在 worker.js 实现跳转逻辑，直接跳转不需要加载html页面速度会快一些吧，但其实估计加载html影响也不大。

可能的问题（副作用）我能想到的是要注意防范 XSS 攻击 ，另外就是如果要展示内容的话可能要增加额外的内容审查API接口，防止被人滥用来传播一些不良信息吧

此外，我也在考虑通过在域名后面添加参数的方式来实现不同的功能，这样就不需要对后端代码做过多修改，只需要前端做好适配就行，例如：项目根域名是：https://lnks.eu.org/

如果要实现文本分享，就可以构造这样的链接：https://lnks.eu.org/?text=URL Encode 过后的文本内容 -> 调用原有的方式缩短构造后的链接，跳转时还是会回到主页面，但主页面前端解析到有url参数是就显示对应的文本

如果要分享图片，可以构造：https://lnks.eu.org/?image=图片URL 或者 小图片可以直接Base64编码（已经上传 -> 调用原有的方式缩短构造后的链接

但这种方式要注意URL 参数的长度限制
